import {
  AirVent,
  BadgeCheck,
  Building2,
  Car,
  ClipboardCheck,
  Clock3,
  Cog,
  Gauge,
  Mail,
  MapPin,
  MessageCircle,
  Navigation,
  PackageCheck,
  Phone,
  Refrigerator,
  SearchCheck,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Truck,
  WashingMachine,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { IconName } from "@/data/services";

export const iconMap: Record<IconName, LucideIcon> = {
  airVent: AirVent,
  refrigerator: Refrigerator,
  washingMachine: WashingMachine,
  cog: Cog,
  car: Car,
  packageCheck: PackageCheck,
  wrench: Wrench,
  clock: Clock3,
  shield: ShieldCheck,
  mapPin: MapPin,
  badge: BadgeCheck,
  snowflake: Snowflake,
  clipboard: ClipboardCheck,
  search: SearchCheck,
  sparkles: Sparkles,
  building: Building2,
  truck: Truck,
  gauge: Gauge,
  phone: Phone,
  message: MessageCircle,
  mail: Mail,
  navigation: Navigation,
};
